#!/bin/bash

#Add sources we need

#enables multiarch for 64 bit systems
sudo dpkg --add-architecture i386
sudo apt-get update

#install bumblebee/primus
sudo apt-get install linux-headers-generic
sudo apt-get install bumblebee primus

#install chromium
sudo apt-get install chromium-browser

#install steam
##wget http://media.steampowered.com/client/installer/steam.deb
##sudo dpkg -i ./steam.deb
##rm steam.deb

#dropbox
##wget https://www.dropbox.com/download?dl=packages/debian/dropbox_1.4.0_amd64.deb
##sudo dpkg -i dropbox_1.4.0_amd64.deb
##rm dropbox_1.4.0_amd64.deb
sudo apt-get install nemo-dropbox

#skype
##wget -O skype-install.deb http://www.skype.com/go/getskype-linux-deb-64
##dpkg -i skype-install.deb
##sudo apt-get -f install
##rm skype-install.deb

#Git and Android
sudo apt-get install git g++-multilib git-core gnupg flex bison gperf zip curl libc6-dev libncurses5-dev:i386 x11proto-core-dev libx11-dev:i386 libreadline6-dev:i386 libgl1-mesa:-dev:i386 mingw32 pngcrush schedtool tofrodos python-markdown libxml2-utils xsltproc zlib1g-dev:i386

sudo apt-get install eclipse

#Google
wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key     add -
sudo sh -c 'echo "deb http://dl.google.com/linux/musicmanager/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
sudo sh -c 'echo "deb http://dl.google.com/linux/talkplugin/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
sudo apt-get update
sudo apt-get install google-talkplugin google-musicmanager-beta

#Netflix
sudo apt-get install ttf-mscorefonts-installer
sudo sh -c 'echo "deb http://ppa.launchpad.net/ehoover/compholio/ubuntu raring main" >> /etc/apt/sources.list.d/ehoover-compholio.list'
sudo apt-get update
sudo apt-get install netflix-desktop

#Heroku
#wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
#heroku login

#libs for gccg
sudo apt-get install libsdl-image1.2:i386 libsdl-net1.2:i386 libsdl-ttf2.0-0:i386 libsdl-mixer1.2:i386

#remove nano, install freedom
sudo apt-get purge nano
sudo apt-get install vim

#Specific Audio Codec setting for Alienware M14xR2
#sudo echo 'options snd-hda-intel model=dell-=m6' >> "/etc/modprobe.d/alsa-base.conf"
#sudo echo 'alias snd-card-0 snd-hda-intel' >> "/etc/modprobe.d/alsa-base.conf"
