#!/bin/bash

#script with manual pointing at folders i use with git repos in them. manual updating of this info for now, ill see about adding automated addition at a later point

cd ~/workspace/RUMAD-Cards-Against-Humanity
git pull
cd ~/workspace/RUMaps/assets/www
git pull
cd ~/bash-scripts
git pull
cd ~/my-website
git pull
