#!/bin/bash

#script with manual pointing at folders i use with git repos in them. manual updating of this info for now, ill see about adding automated addition at a later point

cd ~/workspace/RUMAD-Cards-Against-Humanity
git pull
cd ~/workspace/RUMaps/assets/www
git pull
cd ~/git_repos/bash-scripts
git pull
cd ~/git_repos/my-website
git pull
cd ~/git_repos/mangaget
git pull
cd ~/git_repos/DIFmplayer
git pull
cd ~/git_repos/Pokemon-MMO
git pull
cd ~/git_repos/the.github.pirates/
git pull
