#!/bin/bash

#script with manual pointing at folders i use with git repos in them. manual updating of this info for now, ill see about adding automated addition at a later point


echo Cards against humanity
echo \ 
cd ~/workspace/RUMAD-Cards-Against-Humanity
git pull

echo rumaps
echo \ 
cd ~/workspace/RUMaps
git pull

echo bash scripts
echo \ 
cd ~/git_repos/bash-scripts
git pull

echo website
echo \ 
cd ~/git_repos/my-website
git pull

echo DIFmplayer
echo \ 
cd ~/git_repos/DIFmplayer
git pull

echo Pokemon MMO
echo \ 
cd ~/git_repos/Pokemon-MMO
git pull

echo Github Pirates
echo \ 
cd ~/git_repos/the.github.pirates/
git pull

echo toro script
echo \ 
cd ~/android
git pull

echo manga_downloader
echo \ 
cd ~/git_repos/manga_downloader
git pull

echo fuck
echo \ 
cd ~/workspace/fuck
git pull

echo vim-pathogen
echo \ 
cd ~/git_repos/dotfiles/vim/bundle/vim-pathogen
git pull

echo syntastic
echo \ 
cd ~/git_repos/dotfiles/vim/bundle/syntastic

echo dotfiles
echo \ 
cd ~/git_repos/dotfiles
git pull

echo Distinguished
echo \ 
cd ~/git_repos/vim-distinguished
git pull
