#!/bin/bash

#removes cinnamon, default kernel and mint things i dont want
sudo apt-get purge cinnamon*
sudo apt-get purge mdm*
sudo apt-get purge linux-image* linux headers*

#adds bumblebee repo and gnome3 repo
sudo apt-add-repository ppa:gnome3-team/gnome3
sudo apt-add-repository ppa:bumblebee/stable

#installs liquorix repo 
sudo echo "deb http://liquorix.net/debian sid main" >> /etc/apt/sources.list

#Install all the things (last section is cyanogenmod build related things)
sudo apt-get install '^liquorix-([^-]+-)?keyring.?'
sudo apt-get install gnome linux-headers-liquorix-amd64 linux-image-liquorix-amd64 bumblebee bumblebee-nvida
