#!/bin/bash

##removes cinnamon, default kernel and mint things i dont want
#sudo apt-get purge unity*
#sudo apt-get purge lightdm*


##adds needed repos; check their sites for info on what each contains

add-apt-repository ppa:gnome3-team/gnome3
#add-apt-repository ppa:gnome3-team/gnome3-staging
#add-apt-repository ppa:gnome3-team/gnome3-next

#sudo apt-add-repository ppa:stebbins/handbrake-releases

#sudo apt-add-repository ppa:bumblebee/stable
#sudo apt-add-repository ppa:zhurikhin/primus

apt-add-repository ppa:webupd8team/themes

#sudo add-apt-repository ppa:upubuntu-com/chat

apt-add-repository ppa:ehoover/compholio 

#sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys F24AEA9FB05498B7
#sudo apt-key adv --keyserver pgp.mit.edu --recv-keys 5044912E
#sudo sh -c 'echo "deb http://linux.dropbox.com/ubuntu/ precise main" >> /etc/apt/sources.list.d/dropbox.list'
#sudo -E wget --output-document=/etc/apt/sources.list.d/medibuntu.list http://www.medibuntu.org/sources.list.d/$(lsb_release -cs).list && sudo apt-get --quiet update && sudo apt-get --yes --quiet --allow-unauthenticated install medibuntu-keyring && sudo apt-get --quiet update
#sudo apt-get install app-install-data-medibuntu apport-hooks-medibuntu



##enables multiarch for 64 bit systems
dpkg --add-architecture i386

##installs liquorix and dropbox repos
#echo "deb http://liquorix.net/debian sid main" | sudo tee /etc/apt/sources.list.d/liquorix.list
#echo "deb-src http://liquorix.net/debian sid main" | sudo tee -a /etc/apt/sources.list.d/liquorix.list
#sudo echo "deb http://linux.dropbox.com/ubuntu natty main" >> /etc/apt/sources.list

##Install all the things (last section is cyanogenmod build related things)
apt-get update

#sudo apt-get install '^liquorix-([^-]+-)?keyring.?'
#sudo apt-key adv --keyserver pgp.mit.edu --recv-keys 5044912E


#sudo apt-get install dropbox

apt-get install -y git-core gnupg flex bison gperf zip curl libc6-dev libncurses5-dev:i386 x11proto-core-dev libx11-dev:i386 libreadline6-dev:i386 libgl1-mesa-dev:i386 mingw32 pngcrush schedtool tofrodos python-markdown libxml2-utils xsltproc zlib1g-dev:i386
apt-get install -y g++-multilib

#sudo apt-get install chromium-browser
apt-get install -y eclipse
apt-get install -y mint-themes mint-x-icons

#sudo apt-get install libreoffice
#sudo apt-get purge abiword*

apt-get install -y netflix-desktop
apt-get install -y libsdl-image1.2:i386 libsdl-mixer1.2:i386 libsdl-net1.2:i386 libsdl-ttf2.0-0:i386 libjepg62:i386
apt-get install -y primus bumblebee linux-headers-generic

#echo Download Steam and install it!
#cd Downloads
#curl http://media.steampowered.com/client/installer/steam.deb
#sudo dpkg -i ./steam_latest.deb
##need to update this, steam moved Things.


echo google things!
wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add - 
sh -c 'echo "deb http://dl.google.com/linux/musicmanager/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
sh -c 'echo "deb http://dl.google.com/linux/talkplugin/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
apt-get update 
apt-get -y install google-talkplugin google-musicmanager-beta
rm /etc/apt/sources.list.d/google.list

#chromium flash update
#sudo apt-add-repository ppa:skunk/pepper-flash
#sudo sh -c 'echo ". /usr/lib/pepflashplugin-installer/pepflashplayer.sh" >> /etc/chromium-browser/default'
#sudo apt-get update && sudo apt-get install pepflashplugin-installer

#wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
#heroku login

#sudo apt-get purge lightdm unity*
#sudo apt-get install gdm gnome
#sudo apt-get purge overlay-scrollbar

#sudo apt-get install linux-headers-generic
apt-get -y install build-essential vim xfce4-terminal
apt-get purge nano* gnome-shell-extensions

apt-get -y dist-upgrade
apt-get clean && apt-get autoclean && apt-get -y --purge autoremove

#Specific Audio Codec setting for Alienware M14xR2
#sudo echo 'options snd-hda-intel model=dell-=m6' >> "/etc/modprobe.d/alsa-base.conf"
#sudo echo 'alias snd-card-0 snd-hda-intel' >> "/etc/modprobe.d/alsa-base.conf"
